### ISSUE TITLE
add Adminstrator Bill of Rights to the repo

### ISSUE THREAD

**Issue by ultrasaurus** [cn-security/safe#19]
would be great to add [Adminstrator Bill of Rights doc](https://docs.google.com/document/d/19V_Vx0fdz2HOa31FpPswT9CsUphizfJcwvDJv05aWFs/edit#heading=h.ems5pk2exnlb) as markdown

**Comment by quiqie** [comment]
I can do this.

**Comment by dshaw** [comment]
Thank you, @quiqie. Landed.
