### ISSUE TITLE
Use case presentation on Sysdig Falco

### ISSUE THREAD

**Issue by mfdii** [cn-security/safe#22]
I wanted to propose a use case presentation for the SAFE-WG on [Sysdig Falco](https://github.com/draios/falco). Falco is an open source solution for runtime security. It will detect abnormal behavior inside of containers or container hosts and then notify external systems of the abnormal behavior. This notification can trigger actions such as killing/deleting a container, logging to a collection platform such as an EFK stack, etc.

Some blog posts that highlight how to use Falco:

- [Detecting cryptominers](https://sysdig.com/blog/detecting-cryptojacking-with-sysdigs-falco/)
- [Security dashboards with EFK](https://sysdig.com/blog/kubernetes-security-logging-fluentd-falco/)
- [Deploying Falco to Kubernetes](https://sysdig.com/blog/runtime-security-kubernetes-sysdig-falco/)

The earliest we could present is 5/11.

**Comment by dshaw** [comment]
Thank you, @mfdii.

Folks can find meeting notes and session recording here:
https://docs.google.com/document/d/10iJ3wA7uVI6JMyvIv9qXdxdLCyQeS-djYsTqL_JG3d0/edit
