### ISSUE TITLE
Scope of SAFE proposal

### ISSUE THREAD

**Issue by pragashj** [cn-security/safe#23]
**In scope**
- Exploring and recommending security models
- Identifying and suggesting projects for consideration for CNCF
- Cross-pollinating knowledge by participating and inviting people from other projects and SIGs to transfer security practices
- Bringing in external standards from organization like NIST to projects in CNCF 
- Coming up with a common vocabulary to talk about and understand and talk about security
- Coming up with a few block architecture for secure access and fitting components and projects in to those boxes
- Help TOC when needed with evaluation and recommending specific proposal or projects

**Out of scope**
- This is not a standards body and we won't be creating standards
- Not an uber organization or replacing existing k8s/other projects working groups or SIGs
- Not a compliance body or a certification board for security of individual projects
- This is not related to vulnerability detection and handling and we will not answer any specific questions regarding the state of security of and project or product
- We will not be looking at device or enduser security, unless there is some impact to the cloud security

**Comment by dshaw** [comment]
Thanks, @pragashj for getting us started.

As a reminder for everyone. We're capturing what we want to cover in this Working Group. What's in scope FOR YOU and what's out of scope.

**Comment by dshaw** [comment]
SAFE: Secure Access for Everyone

**In scope:**
* Define what safety a cloud environment entails
* Identify and define what cannot be achieved in a cloud environment
* Identify common actors and personas in a cloud environment
* Partner with CNCF members and projects to identify safety best practices

**Out of scope:**
* Implementation secure access solutions
* Any broad security concern
* Any broad policy concern

**Comment by duglin** [comment]
Initial scope:
- Define the scope of "security" we're concerned with - "app security"? "platform security"? both? others?
- Define common vocab/terms that we'll use in our output doc(s)
- Examine the landscape to see what the community is doing today to address that scope
- Produce a whitepaper of our findings, which might include:
  - a summary of where there is agreement across the current platforms
  - where there is disagreement
  - where we think there are gaps in the current coverage
  - The "agreements" might lead to the paper including a "best practices" section based on community success stories.
- Produce a set of recommendations for the WG's next steps - if any - to be agreed upon by the TOC

Out of scope:
- everything else until we get agreement from the TOC for which "next steps" to work on

**Comment by rcolline** [comment]
#### A couple of things I think we could realistically achieve that would be generally useful:
* Common language and definitions for access control concepts that can be easily understood by developers and consumers of access control systems.  Try to reuse industry standards (XACML, NAGC, etc) where appropriate so we don't add yet another set of terms.
  * Where ever
* Expose and define the tradeoffs that all access systems are governed by.  E.g Expressability vs Explainability.
   * Create ratings for these to allow consumers of access policy systems can understand quickly what the system capabilities are.
   * Through this, we can encourage policy system writers to consider all the tradeoffs and work to reduce the gap between them.
* Define security scenarios (this gets to duglin's comment above).
   * Cloud configuration
   * Application security
   * Identity security
   * Service security
   * etc...
* With our personas, identify which properties of an access policy system matter most and which matter least.

####  Things that we should not think about
* Defining new standards
* Creating reference implementations
* Advocating one system over another.

Thoughts?

**Comment by ckemper67** [comment]
In Scope:

- Understanding the security landscape for users, including legacy access control
- Understanding the existing research body for security and access control
- Understanding aspects of federation of security policy
- Making the tradeoffs between the different approaches transparent for us and for the consumers of our output

Out of scope:
- Defining a standard
- Recommending a standard
- Implementing a standard

**Comment by prabath** [comment]
Hope I am not duplicating the things we already discussed in this thread..

In scope:

- Define best practices/patterns in secure access and produce a document on the same
- Identify and highlight the ant-patterns

**Comment by ultrasaurus** [comment]
In scope
* What is a secure architecture that spans cloud and on-prem deployments?
* How are requests authorized?
* How do we know a service should be authorized to handle a request?
* How do we know a user should be authorized to make a request?
* How do I audit my policies that control access to my app/infrastructure?
* How do I make sure a user can't use more resources than allowed?

Out of scope
* Code Vulnerability detection, cross-site scripting attacks, SQL injection, etc.
* Protection from Phishing attacks
* Fraud detection
* User generated content moderation
* Spam filtering

**Comment by kbpawlowski** [comment]
In scope:

   - decide if our primary goal is safety (being free from risk) or
   security (being free from danger or threat)
   - select environments that are in scope to be kept safe or secure
   - decide (and prioritize) which threats or risk should be addressed
   - develop a common vocabulary
      - for risks and threats
      - for use cases
      - for environments
      - for tooling
   - develop a consistent and rigorous way of thinking about, describing,
   and solving problems related to risk or threat.

Out of scope:

   - endorsement of specific tools or companies

**Comment by caniszczyk** [comment]
@dshaw I'd like to have a proposal ready for the CNCF TOC on Aug 7th so we can formalize this WG.
