### ISSUE TITLE
Use Case: Cloud Foundry with @sreetummidi

### ISSUE THREAD

**Issue by dshaw** [cn-security/safe#3]
@sreetummidi gave one of the first Use Case presentations, but it was early, most SAFE members have not seen the presentation and the session recording only had video with no audio.

At the 2018-03-30 SAFE Meeting, @sreetummidi agreed to share the presentation again. 🙏 Thank you.

**Comment by pragashj** [comment]
https://youtu.be/DRtl8wK9FwE
