### ISSUE TITLE
2018-08-21 TOC Presentation Prep

### ISSUE THREAD

**Issue by dshaw** [cn-security/safe#43]
* PR SAFE WG before 2018-08-21
  - [x] Assign responsible party for PR? Dan Shaw
  - [x] What date do we want to land it on? Proposed date Thursday, 2018-08-16.
  - [x] 2 page overview of SAFE WG. (No need to present WG overview again. Slides are the anchor for kicking of TOC voting.)
  - [ ] Who will present the presentation? JJ or Sabree

Following quick overview of work, Chris Aniszczyk will kick off TOC voting.

**Comment by dshaw** [comment]
DRAFT PR page

# CNCF SAFE WG Proposal

## TOC Sponsor

Alexis Richardson

## Objective

Safe Access for Everyone (SAFE) Working Group will explore secure access, policy control and safety across the cloud native ecosystem for multi-party, interoperable systems.

## Goals and Expected Outcomes

* Create Key Elements of a Trustworthy System white paper
* Create Cloud Native Policy Architecture white paper
* Container Policy Interface implementations
* Explore specifications for SAFE concerns to propose to the CNCF
* Bring recommendations to the TOC on SAFE concerns projects in CNCF

## Non Goals

* Choose a single identity or security technology
* Be a standards body for creating standards

## Initial Interested Parties

Dan Shaw (@dshaw)
Sarah Allen (@ultrasaurus)
Jeyappragash JJ (@pragashj)
Devarajan P Ramaswamy (@deva)
Kamil Pawlowski (@kbpawlowski)
Geri Jennings (@izgeri)
Howard Huang (@hannibalhuang)
Jason Melo (@jasonmelo)
Torin Sandall (@tsandall)
Sree Tummidi (@sreetummidi)
Christian Kemper (@ckemper67)
Ray Colline (@rcolline)
Doug Davis (@duglin)
Sabree Blackmon (@heavypackets)
Justin Cormack (@justincormack)
Liz Rice (@lizrice)
Erik St. Martin (@erikstmartin)
Cheney Hester (@quiqie)
Erica von Buelow (@ericavonb)
Mark Underwood (@knowlengr)

**Comment by dshaw** [comment]
## Objective

Safe Access for Everyone (SAFE) Working Group will explore secure access, policy control and safety for operators, administrators, developers, and end-users across the cloud native ecosystem.

**Comment by dshaw** [comment]
_Previous iteration_

## Goals and Expected Outcomes

* Create Key Elements of a Trustworthy System white paper
* Create Cloud Native Policy Architecture white paper
* Container Policy Interface implementations
* Explore specifications for SAFE concerns to propose to the CNCF
* Bring recommendations to the TOC on SAFE concerns projects in CNCF

**Comment by ultrasaurus** [comment]
* Members will provide feedback on proposed TOC projects related to SAFE
* Consider additional recommendations to CNCF TOC, such as:
   * specifications that may be needed to address SAFE concerns 
   * project proposals needed to address gaps in the SAFE ecosystem

**Comment by dshaw** [comment]
Thanks, @ultrasaurus.

**Comment by dshaw** [comment]
DRAFT Slides:

https://docs.google.com/presentation/d/1NMzOC50fTCvMBdtkQecMxgh3F_oMkIhfl9gtDcamdXo/edit
