### ISSUE TITLE
SAFE / SIG-Auth sync up

### ISSUE THREAD

**Issue by tallclair** [cn-security/safe#53]
I think it would be a good idea to present the SAFE WG to SIG-Auth again, and have a similar discussion to the one we had in [2018-08-17 meeting](https://docs.google.com/document/d/1JsEv4vk_61UaF9SaHBRzzPGja-bNsHeLqxa53RPVfos/edit#heading=h.jdac2fseijb0).

For a date that works (see [SIG-Auth meeting schedule](https://github.com/kubernetes/community/tree/master/sig-auth#meetings)), I recommend adding a line (should be world-editable) to our [agenda document](https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit#). It would also be helpful to send out a brief introduction to our [email group](https://groups.google.com/forum/#!forum/kubernetes-sig-auth), to brief people before the meeting.

**Comment by dshaw** [comment]
Thanks for having us. We look forward to ongoing collaboration.
