### ISSUE TITLE
Talk proposal: Application Identity in Cloud Foundry and Kubernetes, from the Perspective of an External Service

### ISSUE THREAD

**Issue by izgeri** [cn-security/safe#6]
CyberArk Conjur recently built two new integrations with Pivotal Cloud Foundry / Cloud Foundry and OpenShift (RedHat's implementation of Kubernetes). Through that process, we learned a lot about how applications are uniquely identified in these two systems, and how external services might leverage the internal app identities to reliably privilege appropriate applications to utilize their services. 

I am proposing to speak to the SAFE working group about the current state of each of these systems with respect to application identity, and some lessons learned about potential improvements that could be made.

**Comment by duglin** [comment]
I assume this is related to OSB API right ?  Either way I’d be interested in hearing this. 

-Doug

**Comment by izgeri** [comment]
For one of these integrations we used the OSB API, but I wasn't actually thinking I'd talk much about that. I'm actually more interested in the emerging standards around certificate-based app identity, such as the [SPIFFE standard](https://spiffe.io/) and [CF instance identity](https://github.com/cloudfoundry/diego-release/blob/develop/docs/instance-identity.md).

**Comment by dshaw** [comment]
@izgeri Scheduled for 2018-06-08

**Comment by izgeri** [comment]
Slides are available [here](https://drive.google.com/file/d/1UM7jkc2sI61fS0uv968EVMrCHjr4AN6Y)

**Comment by dshaw** [comment]
Meeting notes: https://docs.google.com/document/d/10iJ3wA7uVI6JMyvIv9qXdxdLCyQeS-djYsTqL_JG3d0/edit

Meeting video recording:
https://www.dropbox.com/s/rmr3231e26zue4j/zoom_0.mp4?dl=0
