### ISSUE TITLE
Draft categories for SAFE Landscape

### ISSUE THREAD

**Issue by ultrasaurus** [cn-security/safe#66]
We need to draft the categories that we'll use for grouping projects in the landscape.

This issue is to create an initial draft, and then we'll discuss at a WG meeting

**Comment by lizrice** [comment]
@izgeri thanks for flagging that. For reference here are what I think are the [relevant meeting notes](https://docs.google.com/document/d/1vkUJcj6m8OzZorgODk_D1bchnByb4EXJLbKf5tcMSXA/edit#heading=h.p0wjx8ruop5j) from the Reference Architecture group

**Comment by izgeri** [comment]
Thanks @lizrice. There are also conversations that have been happening in that [mailing list](https://lists.cncf.io/g/cncf-reference-architecture/topics), and I expect @mfdii and I will have a proposal in the next two weeks (he's away this week).

**Comment by pragashj** [comment]
@evan2645, @sreetummidi please take a look at this

**Comment by izgeri** [comment]
@dshaw do I need to be assigned this issue? I'm not sure how to do that in this repository.

**Comment by izgeri** [comment]
@pragashj @lizrice @ultrasaurus @evan2645 @sreetummidi @dshaw 

[This is the Google document](https://docs.google.com/document/d/1--nMpThR_LyUUBN_7wVBC0L1IGzMAbY7kQkiPVR9sH0/edit?usp=sharing) with notes on what @mfdii and I have worked up so far. It includes an explanation of the purpose of our work as well as a proposed structure of what we have been calling the "Security Landscape".  I will be letting the Reference Architecture mailing list know about this draft as well, and that we will be discussing the draft in this group on Friday.

We are eager to get feedback, and the document is open for comments.

**Comment by izgeri** [comment]
Task breakdown with tasks merged from #69 (I am unable to edit the original issue):

# Define Categories / Sub-categories
- [X] propose initial draft of security-focused landscape
- [X] discuss initial categorization proposal in SAFE WG
- [ ] solicit feedback from subject matter experts
- [ ] solicit feedback from CNCF projects
  - Security and Policy solutions
    - [ ] SPIFFE / SPIRE - Evan
    - [ ] Notary
    - [ ] TUF
    - [ ] OPA - Torin with updater
  - Projects with Security Concerns
    - [ ] gRPC
  - Platforms (consider sub-projects that can be used stand-alone, such as Envoy, Mixer):
    - [ ] Istio
    - [ ] Kubernetes
- [ ] solicit feedback from Reference Architecture group (next meeting October 10)
- [ ] finalize proposal for categorization
- [ ] SAFE WG vote on proposal

# Map Security-Related Projects From CNCF Landscape Into These Categories
TBD

# Potential additional tasks
- [ ] Update landscape to include security landscape

**Comment by ultrasaurus** [comment]
I think this is addressed with https://github.com/cn-security/safe/tree/master/landscape and open issue#124 for further work on categories
