### ISSUE TITLE
ABAC Enterprise use-case discovery

### ISSUE THREAD

**Issue by jasonmelo** [cn-security/safe#9]
Connecting SAFE members with a real-world scenario of ABAC implemented on a graph database with a user friendly RBAC abstraction for users and operators.

- Jason Melo and Christian Kemper discussing a higher level conceptual, architectural and implementation overview on 12/4
- Jason Melo discussing a demo for the SAFE group with ADP Product Owner Michael Hirawady on 13/4, based on this discussion we will propose an upcoming Friday for a show and tell with this group, Date TBD.

**Comment by jasonmelo** [comment]
@jasonmelo met with ADP this week to discuss the ABAC/RBAC models inherent in some existing authorization functionality in their platform. They are on-board to present the concept and how it expresses the SAFE use cases, targeting 4/27 however could do sooner if not needed for Friday's WG weekly session.

**Comment by jasonmelo** [comment]
@dshaw How should we go about getting this on the agenda for the 27th? I'd say allot about 45 minutes for preso and Q&A.

**Comment by dshaw** [comment]
@jasonmelo Let's begin to explore dates following the May 15th TOC meeting. May 25th, as you mentioned, is Memorial Day weekend. I'd be happy to shoot for Friday, 5/18 if that works or look for dates in June.

**Comment by dshaw** [comment]
@jasonmelo Can we do this on 2018-06-15?

**Comment by jasonmelo** [comment]
@dshaw confirmed for 2018-06-15 cc @ultrasaurus

**Comment by jasonmelo** [comment]
Slides from the 06-15 presentation by Mike Hirawady - [ABAC Deck](https://drive.google.com/file/d/1aW1T-_N2qkCXfLthenjMhEQetgLt6SGW/view?usp=sharing)

**Comment by dshaw** [comment]
Meeting notes: https://docs.google.com/document/d/1usB6Xw1GVjW--RkRw1RPypwvUP_E8trtzg9JTO1ZAkM/edit

Meeting video recording:
https://www.dropbox.com/s/t5f057pst5fx09c/GMT20180615-175435_SAFE-WG-Me_1760x900.mp4?dl=0
