### ISSUE TITLE
OPA (Open Policy Agent) presentation

### ISSUE THREAD

**Issue by ultrasaurus** [cn-security/safe#95]
OPA is a CNCF sandbox project

Tim Hinrichs (OPA/Styra) presented OPA and use cases on 2/23/2018

Slides: https://www.slideshare.net/TorinSandall/opa-apis-and-use-case-survey
Recording: https://www.dropbox.com/s/86jfs88pjrogbm6/zoom_0.mp4?dl=0

[Meeting Notes](https://docs.google.com/document/d/1U4x1wynL-JlojF1Qidus97t8bJve3XJWTpc07hHCAxU/edit#)

**Comment by dshaw** [comment]
Meeting video recording:
https://www.dropbox.com/s/86jfs88pjrogbm6/zoom_0.mp4?dl=0
