### ISSUE TITLE
NIST Big Data public working group

### ISSUE THREAD

**Issue by ultrasaurus** [cn-security/safe#96]
Mark Underwood presented on 2018-03-23

[Meeting video recording](https://www.dropbox.com/s/78ebgffwn9w7xgu/zoom_0.mp4?dl=0)
[Slides](https://www.slideshare.net/knowlengr/nist-big-data-public-wg-security-and-privacy-v2)
[Notes](https://docs.google.com/document/d/1H3VOI9-GqRAj_tdPL9sECF1c8t4x_sF1G08PqLzlUWM/edit#heading=h.g2ssty7nv4sz)

**Comment by dshaw** [comment]
Arnab Roy presented on 2018-05-18:

* [Meeting Notes](https://docs.google.com/document/d/1xzJ29fTOJSioqrDuSkvBfsewV2lvgbr8olmDWb4kdPk/edit)
* [Meeting Recording](https://www.dropbox.com/s/mdhy0rqjswjwgch/zoom_0.mp4?dl=0)
* Presentation Slides ?
